version: "3.4"

x-common-variables: &common-variables
  MYSQL_USER: sampleuser
  MYSQL_PASSWORD: samplepassword
  MYSQL_DATABASE: profitabilitydb
  REACT_APP_SERVER_PORT: 8000

services:
  mysql-db:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping -h 3306']
      interval: 10s
      timeout: 2s
      retries: 10
    volumes:
      - ./db/profitability.sql:/docker-entrypoint-initdb.d/profitability.sql
  phpmyadmin:
    depends_on:
      - mysql-db
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin_container
    environment:
      PMA_HOST: mysql-db
    links:
      - mysql-db:mysql-db
    ports:
      - 8090:80
    restart: always
  server:
    build: ./server
    container_name: node_container
    depends_on:
      - mysql-db
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql-db
    ports:
      - 8000:8000
    volumes:
      - ./server:/app
      - /app/node_modules
    links:
      - mysql-db
    command: ["./wait-for-it.sh", "mysql-db:3606", "--", "npm", "start"]
  client:
    build: ./client
    container_name: react_container
    environment:
      <<: *common-variables
      NODE_PATH: src
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
    links:
      - server
    command: npm run start
